#introduction to numpy

In [9]:
import numpy as np



In [10]:
even=[6, 3,5,6,32, 43,5,10]
len(even)



8

In [11]:
even_array=np.array(even)
even_array[1:4]

type(even_array)
even_array.ndim

np.ones(3,dtype=np.float16)

array([1., 1., 1.], dtype=float16)

In [26]:
np.random.randint(0,10)

1

In [30]:
np.random.seed(4)
np.random.randint(0,10)

7

In [38]:
np.random.seed(2024)
x=np.random.randint(1,10, size=50000)
x_list=x.tolist()


In [42]:
a=[8,9,7]
sq=[]
for i in a:
    sq.append(i ** 2)





UsageError: Line magic function `%%time` not found.


In [45]:

%%time 
sq=[i **2 for i in a]
sq

CPU times: total: 0 ns
Wall time: 0 ns


[64, 81, 49]

In [51]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [53]:
x=np.array([4,5])
y=np.array([0,3])
x*y

array([ 0, 15])

statistics

In [55]:
np.random.seed(0)
x=np.random.randint(1,20, size=40)
x

array([13, 16,  1,  4,  4,  8, 10, 19,  5,  7, 13,  2,  7,  8, 15, 18,  6,
       14,  9, 10, 17,  6, 16, 16,  1, 19,  4, 18, 15,  8,  1,  2, 10,  1,
       11,  4, 12, 19,  3,  1])

In [60]:
np.median(x)

8.5

In [68]:
from scipy.stats import mode

mode(x)

ModeResult(mode=1, count=5)

In [69]:
np.std(x) #standard deviation

5.943010600697259

2D array

In [70]:
matrix= np.array([[3,3,5],[5,3,6],[9,3,2]])
matrix

array([[3, 3, 5],
       [5, 3, 6],
       [9, 3, 2]])

In [75]:
matrix[1:,1:]

array([[3, 6],
       [3, 2]])

In [76]:
matrix[:, :2]

array([[3, 3],
       [5, 3],
       [9, 3]])

dot product/ matrix manipulation

In [81]:
A=np.array([[1,2,3],[4,3,5]])
B=np.array([[4,3] , [5,7],[9,2]])
A

array([[1, 2, 3],
       [4, 3, 5]])

In [82]:
A.shape

(2, 3)

In [83]:
B.shape

(3, 2)

In [85]:
op=np.dot(A,B)
op

array([[41, 23],
       [76, 43]])

In [93]:
det=np.linalg.det(op)

In [94]:
np.round(det,2)

15.0

In [95]:
np.linalg.inv(op)

array([[ 2.86666667, -1.53333333],
       [-5.06666667,  2.73333333]])

#converting 2D array to 1D array

In [96]:
x=np.array([[4,5,6],[3,2,7]])
print(x)
print(f"dimension ={x.ndim}")

[[4 5 6]
 [3 2 7]]
dimension =2


In [99]:
x_1d=x.flatten()
print(x_1d)
print(f"dimension ={x_1d.ndim}")

[4 5 6 3 2 7]
dimension =1


converting 1D array to 2D array / .reshape()

In [103]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
x.reshape(1,-1) #row =1 column is unknown.

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [106]:
x.reshape(-1,1) # row is unknown

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [107]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
x.sum(axis=1) #horizontal sum

array([ 6, 15])

In [109]:
x.sum(axis=0) # axis=0 vertical sum

array([5, 7, 9])