In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [7]:
df=pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [10]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
model=LinearRegression()

In [15]:
X=df[['area','bedrooms','age']]
y=df['price']

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [18]:
model.fit(X_train,y_train)

LinearRegression()

In [20]:
y_pred=model.predict(X_test)
y_pred

array([651388.88888889, 402777.77777778])

In [23]:
model.predict([[3000,3,40]])

c:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([300000.])

In [24]:
model.coef_

array([-2.77777778e+01,  5.27777778e+04, -1.19444444e+04])

In [25]:
model.intercept_

702777.7777777798

In [30]:
-2.77777778e+01*3000+5.27777778e+04*3+-1.19444444e+04*40+702777.7777777798

300000.00177777983

In [37]:
d=pd.read_csv("hiring.csv")
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [39]:
d.experience=d.experience.fillna(0)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [42]:
d['test_score(out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     NaN
7     7.0
Name: test_score(out of 10), dtype: float64

In [41]:
import math
median=math.floor(d['test_score(out of 10)'].median())
median

8

In [44]:
d['test_score(out of 10)']=d['test_score(out of 10)'].fillna(median)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [45]:
model.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])

LinearRegression()

In [46]:
model.predict([[2,9,6]])

c:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])